server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_IP:localhost}:5432/micro-service
    username: username
    password: password
  jpa:
    open-in-view: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: "false"
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: "true"
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: update
    show-sql: "true"
